version: '3'
services:
  dev:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - cargo-cache:/usr/local/cargo/registry
    command: sleep infinity
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=debug

volumes:
  cargo-cache: 